a=input('Enter the First number : ')
b=input('Enter the Second : ')
a=int(a)
b=int(b)
Sum=(a+b)
Sub= (a-b)
mul = (a*b)
Div = (a/b)
Sum = int(Sum)
Sub = int(Sub)
mul = int(mul)
Div = int(Div)
print('Addition : ', Sum)
print('Subtraction : ', Sub)
print('Multiplication : ', mul)
print('Division : ', Div)