file= open('output.txt','w')
file2=input('Enter text to write to the file :')
write_file=file.write(file2)
print('Data successfully written to the output.txt')
file.close()

file_append=input("\n\nEnter Additional text to Append :")
file3=open('output.txt','a')
file4=file3.writelines('\n')
file4=file3.writelines(file_append)
print('Data Successfully appended')
file3.close()
file5=open('output.txt','r')
print('Final content of the output.txt :\n')
file6=file5.read()
print(file6)
file5.close()
